### ISSUE TITLE
OMP: Error #13: Assertion failure at kmp_affinity.cpp(583)

### ISSUE THREAD

**Issue by ryanalvita** [CNES/pangeo-pytide#12]
# **🐞 Bug Report**

## **1. Description**
Hi pangeo-pytide devs, I found a bug when trying to run the "Quick Tutorial" in the readme.md, specifically when running this line:
```python
w = wt.harmonic_analysis(h, f, vu)
```

It seems that I've received this error:
```
..OMP: Error #13: Assertion failure at kmp_affinity.cpp(583).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see http://www.intel.com/software/products/support/.
Aborted (core dumped)
```

Could you assist me regarding this matter? Thank you in advance.

---

### **2. To Reproduce**
1. I follow the steps in the "How to Install" part in the readme
2. Continue with trying the "Quick Tutorial" part. 

---

### **3. Expected behaviour**
I would expect that the function will run and i will get the results for the tidal height part. 

---

### **4. My environment**
* OS: Debian GNU/Linux 12 (bookworm)
* Python version: v3.11
* Pytide version: v1.2.6

**Comment by fbriol** [comment]
This project is archived and no longer maintained. The functionality of this project has been integrated into the [pyfes](https://github.com/CNES/pangeo-pytide) project.
