### ISSUE TITLE
Prediction of past timeseries not correct in tests

### ISSUE THREAD

**Issue by jorgsk** [CNES/pangeo-pytide#2]
I have installed pytide from with conda-forge and tried it with some sample data. I got incorrect results (wildly), and looked at the tests. When I run the following test code

The following test

    def test_analysis(self):
        with netCDF4.Dataset(self.DATASET) as dataset:
            time = (dataset['time'][:] * 1e-6).astype("datetime64[s]")
            h = dataset['ocean'][:] * 1e-2

        wt = pytide.WaveTable()
        f, vu = wt.compute_nodal_modulations(time)
        w = wt.harmonic_analysis(h, f, vu)
        delta = h - wt.tide_from_tide_series(time, w)

        self.assertAlmostEqual(delta.mean(), 0, delta=1e-16)
        self.assertAlmostEqual(delta.std(), 0, delta=1e-12)

I plot the following for h against wt.tide_from_tide_series(time, w)  when restricting to the first 1000 timesteps

![pytide_mismatch](https://user-images.githubusercontent.com/761677/73255298-34961a00-41c0-11ea-892e-d18f528d60cf.png)

This doesn't seem right. Could there be something with the latest conda-forge version?

**Comment by fbriol** [comment]
Can you try it with the test module generated on my repository (only for python 3.7):

```conda install -c fbriol pytide```

**Comment by fbriol** [comment]
Corrected with the new release 1.2.2

![Corrected](https://user-images.githubusercontent.com/397386/73562134-c3be5e80-445a-11ea-9dfb-848fb8a064c0.png)
