### ISSUE TITLE
Inference

### ISSUE THREAD

**Issue by rsignell-usgs** [CNES/pangeo-pytide#3]
pangeo-pytide doesn't do inference like in [Utide](https://www.researchgate.net/publication/280722790_Unified_tidal_analysis_and_prediction_using_the_UTide_Matlab_functions?channel=doi&linkId=55ff3e5808aeba1d9f8404fb&showFulltext=true), right? 

I've been using the python version of Utide for coastal oceanographic data at: 
https://github.com/wesleybowman/UTide

But perhaps you don't need inference because you are using pangeo-pytide on models that are long duration and are not noisy?

**Comment by fbriol** [comment]
That's right. We developed this software to perform analyses on high-resolution models with dask.
