### ISSUE TITLE
state of my fork / anything you want to incorporate?

### ISSUE THREAD

**Issue by jerabaul29** [CNES/pangeo-pytide#8]
Just FYI I have on my fork (see: https://github.com/jerabaul29/pangeo-pytide/tree/add-example ):

- a slightly modified code so that I do not need any MKL stuff. Then it is easy to build. May be of interest for most "casual users" who just want to perform a few time series fitting and predictions at a "few" locations.

- I have added some data from real world observations, see https://github.com/jerabaul29/pangeo-pytide/blob/add-example/examples/example_tide_from_tide_series.ipynb . The package seems to work also very nicely with these field data that have both tidal and weather contributions, and to identify well the tide contribution.

- I have created a wrapper class around your examples trying to make sure that the user cannot shoot himself in the foot due to the timestamps issues etc. Basically all it takes in and out is datetimes with UTC timezone. See for example:

https://github.com/jerabaul29/pangeo-pytide/blob/add-example/examples/example_pytide_analyzer.ipynb

Is there anything you want to integrate to your repo? I understand that we may have quite different user cases, so maybe you do not want to get my changes pushed to your work. I think the real world test could be interesting for most users though. I also wonder if it may be a good idea to have some build flag to switch on / off MKL easily, so that everybody is easily able to build. If this is of interest I can work on specific pull requests, we should just agree what goes in which pull request.

**Comment by fbriol** [comment]
I haven't had time to look yet. I am in the process of correcting the problem for MKL. The tests are running on Azure, we still have to wait. I'm trying to look at it soon. Thanks a lot.

**Comment by jerabaul29** [comment]
Ok. No worries. Thank you a lot, you did all the hard work writing this package in the first place :) .

Just by curiosity, are you able to test yourself on a recent Ubuntu with conda or similar? Or are you packages always only tested on Azure?

**Comment by fbriol** [comment]
I was able to reproduce the problem on my computer. The origin of the problem is due to the fact that the MKL libraries are packaged differently between the main and conda-forge channels. Yesterday I had just tested the import and not the execution...

**Comment by jerabaul29** [comment]
Ok, thanks for confirming that this is reproducible.
