### ISSUE TITLE
using FES2014 files for prediction

### ISSUE THREAD

**Issue by apatlpo** [CNES/pangeo-pytide#9]
Is it possible to use FES2014 netcdf files in order to make tidal predictions?

I was not able to install easily pyfes and wondered wether we could do this.

**Comment by fbriol** [comment]
No, this is not possible. For this, you can use the FES code which is on [BitBucket](https://bitbucket.org/cnes_aviso/fes/src/master/). There is a python library that allows you to calculate the tide from the FES grids.
I asked Guillaume to create a new directory to migrate this project on GitHub.
